name: Fly Deploy
on: [workflow_dispatch]
  # push:
  #   branches:
  #     - main
jobs:
  deployTodo:
    name: Deploy Todo0 app
    runs-on: ubuntu-latest
    # runs-on: ubuntu-22.04
    concurrency: todo-app
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy -c ./deployment/todosrv.fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_TODO_TOKEN }}

  deployWiki:
    name: Deploy Wiki0 app
    runs-on: ubuntu-latest
    concurrency: wiki-app
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy -c ./deployment/wikisrv.fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_WIKI_TOKEN }}