name: Fly Deploy
on: [workflow_dispatch]
  # push:
  #   branches:
  #     - main
jobs:
  deployWikiAuth:
    name: Deploy Wiki0 Auth Server
    runs-on: ubuntu-latest
    concurrency: wiki-auth
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy -c ./deployment/wikiauthsrv.fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_WIKI_AUTH_TOKEN }}

  deployTodoAuth:
    name: Deploy Todo0 Auth Server
    runs-on: ubuntu-latest
    concurrency: todo-auth
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy -c ./deployment/todoauthsrv.fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_TODO_AUTH_TOKEN }}
