name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deployTodo:
    name: Deploy Todo0 app
    runs-on: ubuntu-latest
    # runs-on: ubuntu-22.04
    concurrency: todo-app
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: fly deploy -c ./deployment/todosrv.fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_TODO_TOKEN }}

  deployWiki:
    name: Deploy Wiki0 app
    runs-on: ubuntu-latest
    concurrency: wiki-app
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: fly deploy -c ./deployment/wikisrv.fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_WIKI_TOKEN }}

  deployWikiAuth:
    name: Deploy Wiki0 Auth Server
    runs-on: ubuntu-latest
    concurrency: wiki-auth
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: fly deploy -c ./deployment/wikiauthsrv.fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_WIKI_AUTH_TOKEN }}

  deployTodoAuth:
    name: Deploy Todo0 Auth Server
    runs-on: ubuntu-latest
    concurrency: todo-auth
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: fly deploy -c ./deployment/todoauthsrv.fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_TODO_AUTH_TOKEN }}
